---
- hosts: all
  tasks:
    - name: "Update packages and upgrade"
      apt:
        update_cache: true
        upgrade: dist
        force_apt_get: true
    - name: "Install Apache server"
      apt:
        name: apache2
        state: latest
    - name: "Create document root"
      file:
        path: "/var/www/html"
        state: directory
        owner: "www-data"
        mode: 0755
    - name: "Enable Apache on Firewall"
      ufw:
        rule: allow
        port: "80"
        proto: tcp
    - name: "restart apache2 service"
      service:
        name: apache2
        state: started
    - name: Git checkout files
      ansible.builtin.git:
        repo: 'https://github.com/zapitest/ansible-files'
        dest: /root/ansible/files
        update: "yes"
    - name: Copy file1 to destination
      template:
        src: "/root/ansible/files/file1"
        dest: "/root/file1.copied"
